# Generated by Django 5.2.7 on 2025-10-28 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(help_text='The exact topic the user requested.', max_length=255)),
                ('duration_input', models.CharField(help_text="User's input on time/duration (e.g., '3 days', '2 hours').", max_length=50)),
                ('generated_content', models.TextField(help_text='The full structured study plan or quiz generated by the AI.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, help_text='General topic category for grouping.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='study_core.studytopic')),
            ],
        ),
    ]
