# Generated by Django 5.2.7 on 2025-11-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_core', '0002_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('duration_hours', models.IntegerField(default=10, help_text='Total estimated study hours.')),
                ('is_published', models.BooleanField(default=False, help_text='If checked, the course is visible to learners.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topics', models.ManyToManyField(blank=True, related_name='courses', to='study_core.topic')),
            ],
            options={
                'verbose_name': 'Study Course',
                'verbose_name_plural': 'Study Courses',
                'ordering': ['name'],
            },
        ),
    ]
