# study_core/models.py - FULLY UPDATED
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify

User = get_user_model()

class StudyTopic(models.Model):
    """A model for general topics the user studies (e.g., 'Python', 'React')."""
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class StudySession(models.Model):
    """
    Stores a single AI-generated study plan or quiz session.
    The content is saved as plain text or JSON string in the 'generated_content'.
    """
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='study_sessions')
    topic_name = models.CharField(max_length=255, help_text="The exact topic the user requested.")
    topic = models.ForeignKey(
        StudyTopic, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        help_text="General topic category for grouping."
    )
    duration_input = models.CharField(max_length=50, help_text="User's input on time/duration (e.g., '3 days', '2 hours').")
    generated_content = models.TextField(help_text="The full structured study plan or quiz generated by the AI.")
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username} | {self.topic_name} ({self.created_at.strftime("%Y-%m-%d")})'


class Topic(models.Model):
    """Represents a specific subject or topic that can be studied."""
    
    # The name of the topic, e.g., 'Thermodynamics' or 'Python Basics'
    name = models.CharField(max_length=100, unique=True)
    
    # A brief description of the topic
    description = models.TextField(blank=True)
    
    # Flag to indicate if the topic is active/visible to learners
    is_active = models.BooleanField(default=True)
    
    # Optional: Date when the topic was created
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name = "Study Topic"
        verbose_name_plural = "Study Topics"


class Course(models.Model):
    """Represents a structured learning course that can span multiple topics."""
    
    # --- Basic Fields ---
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True)
    description = models.TextField(blank=True)
    
    # --- Link to Topics (Many-to-Many Relationship) ---
    # A Course can cover many Topics, and a Topic can be part of many Courses.
    topics = models.ManyToManyField('Topic', related_name='courses', blank=True)
    
    # --- Course Structure/Duration ---
    duration_hours = models.IntegerField(default=10, help_text="Total estimated study hours.")
    
    # --- Status ---
    is_published = models.BooleanField(default=False, help_text="If checked, the course is visible to learners.")
    
    # --- Metadata ---
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['name']
        verbose_name = "Study Course"
        verbose_name_plural = "Study Courses"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)