from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class StudyTopic(models.Model):
    """A model for general topics the user studies (e.g., 'Python', 'React')."""
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    
    def __str__(self):
        return self.name

    


class StudySession(models.Model):
    """
    Stores a single AI-generated study plan or quiz session.
    The content is saved as plain text or JSON string in the 'generated_content'.
    """
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='study_sessions')

    
    topic_name = models.CharField(max_length=255, help_text="The exact topic the user requested.")
    topic = models.ForeignKey(
        StudyTopic, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        help_text="General topic category for grouping."
    )
    duration_input = models.CharField(max_length=50, help_text="User's input on time/duration (e.g., '3 days', '2 hours').")
    
    
    generated_content = models.TextField(help_text="The full structured study plan or quiz generated by the AI.")
    
    
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username} | {self.topic_name} ({self.created_at.strftime("%Y-%m-%d")})'